/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.convercao;

/**
 *
 * @author Aluno
 */
public class Formulario extends javax.swing.JFrame {

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
    }       
    Double resultado;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBox1 = new javax.swing.JComboBox<>();
        txtCampo = new javax.swing.JTextField();
        ComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtResultado = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboBox1.setForeground(new java.awt.Color(51, 51, 255));
        ComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quilômetro (km)", "Metro (m)", "Decímetro (dm)", "Centímetro (cm)", "Milímetro (mm)" }));
        ComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox1ActionPerformed(evt);
            }
        });

        txtCampo.setBackground(new java.awt.Color(51, 51, 255));
        txtCampo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCampoActionPerformed(evt);
            }
        });

        ComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ComboBox2.setForeground(new java.awt.Color(51, 51, 255));
        ComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quilômetro (km)", "Metro (m)", "Decímetro (dm)", "Centímetro (cm)", "Milímetro (mm)" }));
        ComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Comprimento");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Quero converter:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText("Para:");

        jButton1.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 255));
        jButton1.setText("=");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtResultado.setBackground(new java.awt.Color(51, 51, 255));
        txtResultado.setFont(new java.awt.Font("sansserif", 0, 12)); // NOI18N
        txtResultado.setForeground(new java.awt.Color(255, 255, 255));
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCampo, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(161, 161, 161))
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(txtResultado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(ComboBox2, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ComboBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(ComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txtResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox1ActionPerformed

    private void txtCampoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCampoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCampoActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        var campo = Double.parseDouble(txtCampo.getText());
        var box1  = ComboBox1.getSelectedItem().toString();
        var box2  = ComboBox2.getSelectedItem().toString();
      
        switch(box1){
            case "Quilômetro (km)":
                if("Metro (m)" == box2){
                    resultado = campo * 1000;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Quilômetro (km)":
                if("Decímetro (dm)" == box2){
                    resultado = campo * 10000;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Quilômetro (km)":
                if("Centímetro (cm)" == box2){
                    resultado = campo * 100000;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Quilômetro (km)":
                if("Milímetro (mm)" == box2){
                    resultado = campo * 1000000;
                }
        }
        txtResultado.setText(resultado.toString());  
        switch(box1){
            case "Metro (m)":
                if("Quilômetro (km)" == box2){
                    resultado = campo / 1000;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Metro (m)":
                if("Decímetro (dm)" == box2){
                    resultado = campo * 10;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Metro (m)":
                if("Centímetro (cm)" == box2){
                    resultado = campo * 100;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Metro (m)":
                if("Milímetro (mm)" == box2){
                    resultado = campo * 1000;
                }
        }
        txtResultado.setText(resultado.toString());  
        
        switch(box1){
            case "Decímetro (dm)":
                if("Quilômetro (km)" == box2){
                    resultado = campo / 10000;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Decímetro (dm)":
                if("Metro (m)" == box2){
                    resultado = campo / 10;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Decímetro (dm)":
                if("Centímetro (cm)" == box2){
                    resultado = campo * 10;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Decímetro (dm)":
                if("Milímetro (mm)" == box2){
                    resultado = campo * 100;
                }
        }
        txtResultado.setText(resultado.toString());
                        switch(box1){
            case "Centímetro (cm)":
                if("Quilômetro (km)" == box2){
                    resultado = campo / 100000;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Centímetro (cm)":
                if("Metro (m)" == box2){
                    resultado = campo / 100;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Centímetro (cm)":
                if("Decímetro (dm)" == box2){
                    resultado = campo / 10;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Centímetro (cm)":
                if("Milímetro (mm)" == box2){
                    resultado = campo * 10;
                }
        }
        txtResultado.setText(resultado.toString());
                txtResultado.setText(resultado.toString());
        switch(box1){
            case "Milímetro (mm)":
                if("Quilômetro (km)" == box2){
                    resultado = campo / 10000000;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Milímetro (mm)":
                if("Metro (m)" == box2){
                    resultado = campo / 1000;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Milímetro (mm)":
                if("Decímetro (dm)" == box2){
                    resultado = campo / 100;
                }
        }
        txtResultado.setText(resultado.toString());
        
        switch(box1){
            case "Milímetro (mm)":
                if("Centímetro (cm)" == box2){
                    resultado = campo / 10;
                }
        }
        txtResultado.setText(resultado.toString());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtCampo.setText(" ");
        txtResultado.setText(" ");
        ComboBox1.setSelectedIndex(-1);
        ComboBox2.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Formulario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Formulario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox1;
    private javax.swing.JComboBox<String> ComboBox2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtCampo;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
